apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: viim-ml-service
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containers:
      - image: PLACEHOLDER
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: '2'
            memory: 2Gi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 3
          tcpSocket:
            port: 8080
      timeoutSeconds: 600

